version: '3.7'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    networks:
      - red
    restart: always
    environment:
      DEFAULT_HOST: ${domain}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - ./vhostd:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  livestream:
    image: jasonrivers/nginx-rtmp
    container_name: livestream
    restart: always
    networks:
      - red
    ports:
      - "1935:1935"
    volumes:
      - ./web/public:/opt/nginx/html:ro
      - ./web/config:/opt/nginx/conf/
    environment:
      VIRTUAL_HOST: ${domain}
      LETSENCRYPT_HOST: ${domain}
      LETSENCRYPT_EMAIL: ${email}

  video-converter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: video-converter
    restart: always
    networks:
      - red
    volumes:
      - ./uploads:/app/uploads
      - ./hls:/app/hls
    ports:
      - "3001:3001"

networks:
  red:
    driver: "bridge"
